name: Build FFmpeg on push
on:
  push:
    branches:
      - master
      
env:
  ffmpeg_version: n4.3.1
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: ./dependencies.sh
        
      - name: Move ffmpeg-windows-build-helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
        
      - name: Compile FFmpeg using ffmpeg-windows-build-helpers
        run: ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=$ffmpeg_version --gcc-cpu-count=2 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi
        
      - name: 7-Zip FFmpeg win64 nonfree
        working-directory: sandbox/win64/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}
        run: 7z a ffmpeg-win64-nonfree.7z ffmpeg.exe ffprobe.exe ffplay.exe -mx=9
        
      - name: 7-Zip FFmpeg win32 nonfree
        working-directory: sandbox/win32/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}
        run: 7z a ffmpeg-win32-nonfree.7z ffmpeg.exe ffprobe.exe ffplay.exe -mx=9
        
      - name: Upload FFmpeg win64 nonfree
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-${{ env.ffmpeg_version }}-win64-nonfree
          path: sandbox/win64/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}/ffmpeg-win64-nonfree.7z
          
      - name: Upload FFmpeg win32 nonfree
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-${{ env.ffmpeg_version }}-win32-nonfree
          path: sandbox/win32/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}/ffmpeg-win32-nonfree.7z
          
  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download all builds
        uses: actions/download-artifact@v2
        
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "#${{ github.run_number }}"
          release_name: "${{ env.ffmpeg_version }} #${{ github.run_number }}"
          draft: false
          prerelease: false
          
      - name: Upload FFmpeg win64 nonfree Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ffmpeg-${{ env.ffmpeg_version }}-win64-nonfree/ffmpeg-win64-nonfree.7z
          asset_name: ffmpeg-${{ env.ffmpeg_version }}-win64-nonfree.7z
          asset_content_type: application/x-7z-compressed
          
      - name: Upload FFmpeg win32 nonfree Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ffmpeg-${{ env.ffmpeg_version }}-win32-nonfree/ffmpeg-win32-nonfree.7z
          asset_name: ffmpeg-${{ env.ffmpeg_version }}-win32-nonfree.7z
          asset_content_type: application/x-7z-compressed