name: Build stable FFmpeg
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  ffmpeg-version: n4.3.1
      
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: ./dependencies.sh
        
      - name: Move helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
          
      - name: Compile FFmpeg
        run: ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=n4.3.1 --gcc-cpu-count=2 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=multi
          
      - name: Upload FFmpeg win64 with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win64-nonfree
          path: sandbox/win64/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg-version }}/ffmpeg.exe
          
      - name: Upload FFmpeg win64 GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win64-gpl
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ffmpeg.exe
          
      - name: Upload FFplay win64 with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win64-nonfree
          path: sandbox/win64/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg-version }}/ffplay.exe
          
      - name: Upload FFplay win64 GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win64-gpl
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/ffplay.exe
          
      - name: Upload FFmpeg win32 with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win32-nonfree
          path: sandbox/win32/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg-version }}/ffmpeg.exe
          
      - name: Upload FFmpeg win32 GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win32-gpl
          path: sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ffmpeg.exe
          
      - name: Upload FFplay win32 with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win32-nonfree
          path: sandbox/win32/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg-version }}/ffplay.exe
          
      - name: Upload FFplay win32 GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win32-gpl
          path: sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/ffplay.exe
          
      - name: Upload x264 win64
        uses: actions/upload-artifact@v2
        with:
          name: x264-win64
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x264.exe
          
      - name: Upload x264 win64 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x264-win64-all-bitdepth
          path: sandbox/win64/x264_all_bitdepth/x264.exe
          
      - name: Upload x265 win64
        uses: actions/upload-artifact@v2
        with:
          name: x265-win64
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x265.exe
          
      - name: Upload x265 win64 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x265-win64-all-bitdepth
          path: sandbox/win64/x265_all_bitdepth/8bit/x265.exe
          
      - name: Upload x264 win32
        uses: actions/upload-artifact@v2
        with:
          name: x264-win32
          path: sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/x264.exe
          
      - name: Upload x264 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x264-win32-all-bitdepth
          path: sandbox/win32/x264_all_bitdepth/x264.exe
          
      - name: Upload x265 win32
        uses: actions/upload-artifact@v2
        with:
          name: x265-win32
          path: sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32/bin/x265.exe
          
      - name: Upload x265 win32 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x265-win32-all-bitdepth
          path: sandbox/win32/x265_all_bitdepth/8bit/x265.exe