name: Build FFmpeg on push
on:
  push:
    paths:
      - ffmpeg-windows-build-helpers
      - dependencies.sh
      - .github/workflows/build-on-push.yaml
    branches-ignore:
      - dependabot/**
      
env:
  ffmpeg_version: n5.0
  
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [win64, win32]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
          
      - name: Install dependencies
        run: ./dependencies.sh
        
      - name: Get current ffmpeg-windows-build-helpers git commit SHA
        id: helper-git-sha
        working-directory: ffmpeg-windows-build-helpers
        run: echo ::set-output name=git-sha::$(git rev-parse --short HEAD)
        
      - name: Move ffmpeg-windows-build-helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
        
      - name: Get current date & time before build
        id: date-time-before
        run: echo ::set-output name=date-time::$(date +'%Y-%m-%d %H:%M')
        
      - name: Compile FFmpeg using ffmpeg-windows-build-helpers
        run: ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=$ffmpeg_version --gcc-cpu-count=$(nproc) --disable-nonfree=n --sandbox-ok=y --compiler-flavors=${{ matrix.os }}
        
      - name: Get current date & time after build
        id: date-time-after
        run: |
          echo ::set-output name=date-time::$(date +'%Y-%m-%d %H:%M')
          echo ::set-output name=date-time-tag::$(date +'%Y-%m-%d-%H-%M')
          
      - name: Upload FFmpeg ${{ matrix.os }} nonfree
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ env.ffmpeg_version }}-${{ steps.helper-git-sha.outputs.git-sha }}-${{ matrix.os }}-nonfree
          path: sandbox/${{ matrix.os }}/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}/ffmpeg.exe
          
      - name: Upload FFprobe ${{ matrix.os }} nonfree
        uses: actions/upload-artifact@v3
        with:
          name: ffprobe-${{ env.ffmpeg_version }}-${{ steps.helper-git-sha.outputs.git-sha }}-${{ matrix.os }}-nonfree
          path: sandbox/${{ matrix.os }}/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}/ffprobe.exe
          
      - name: Upload FFplay ${{ matrix.os }} nonfree
        uses: actions/upload-artifact@v3
        with:
          name: ffplay-${{ env.ffmpeg_version }}-${{ steps.helper-git-sha.outputs.git-sha }}-${{ matrix.os }}-nonfree
          path: sandbox/${{ matrix.os }}/ffmpeg_git_with_fdk_aac_${{ env.ffmpeg_version }}/ffplay.exe
          
    outputs:
      date-time-before: ${{ steps.date-time-before.outputs.date-time }}
      date-time-after: ${{ steps.date-time-after.outputs.date-time }}
      date-time-after-tag: ${{ steps.date-time-after.outputs.date-time-tag }}
      helper-git-sha: ${{ steps.helper-git-sha.outputs.git-sha }}
      
  archive:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win64, win32]
        
    steps:
      - name: Download FFmpeg ${{ matrix.os }} nonfree
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree
          
      - name: Download FFprobe ${{ matrix.os }} nonfree
        uses: actions/download-artifact@v3
        with:
          name: ffprobe-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree
          
      - name: Download FFplay ${{ matrix.os }} nonfree
        uses: actions/download-artifact@v3
        with:
          name: ffplay-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree
          
      - name: 7-Zip FFmpeg ${{ matrix.os }} nonfree
        run: 7z a ffmpeg-${ffmpeg_version}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree.7z ffmpeg.exe ffprobe.exe ffplay.exe -mx9
        
      - name: Upload FFmpeg archive ${{ matrix.os }} nonfree
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-archive-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree
          path: ffmpeg-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-${{ matrix.os }}-nonfree.7z
          
  release:
    needs: [build, archive]
    runs-on: ubuntu-latest
    steps:
      - name: Download FFmpeg archive win64
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-archive-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-win64-nonfree
          
      - name: Download FFmpeg archive win32
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-archive-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-win32-nonfree
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.ffmpeg_version }} ${{ needs.build.outputs.date-time-after }} ${{ needs.build.outputs.helper-git-sha }}
          tag_name: m-${{ needs.build.outputs.date-time-after-tag }}
          body: |
            FFmpeg nonfree ${{ env.ffmpeg_version }} built on ${{ needs.build.outputs.date-time-after }} started at ${{ needs.build.outputs.date-time-before }}
            Using ffmpeg-windows-build-helpers git-${{ needs.build.outputs.helper-git-sha }}
          files: |
            ffmpeg-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-win64-nonfree.7z
            ffmpeg-${{ env.ffmpeg_version }}-${{ needs.build.outputs.helper-git-sha }}-win32-nonfree.7z
            
  delete_old:
    name: Delete older pre-releases
    runs-on: ubuntu-latest
    steps:
      - name: Delete older pre-releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: a
        env:
          GITHUB_TOKEN: ${{ github.token }}